name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  #job의 이름
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH(원격 접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script: |
            cd /home/ubuntu/github-action-spring
            git pull origin main
            cd github-action-server
            rm -rf src/main/resources/application.properties
            rm -rf src/main/resources/application.yml
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
            chmod +x gradlew
            ./gradlew clean build
            sudo fuser -k 8080/tcp || true
            nohup java -jar build/libs/*SNAPSHOT.jar > app.log 2>&1 &
